language: php
php:
- '5.5'
- '5.4'
before_script:
- travis_retry composer self-update
- travis_retry composer install --prefer-source --no-interaction --dev
script:
- php vendor/bin/phpunit
notifications:
  slack:
    secure: AVVFQQcu1vFP1IA+NuONKgtPyLKNE3Sbq8Tlr0WFcqsVCU7B/Onb+yiVBjvZuq7RCWTy1H34ChyEqaaP00ztGKiDRFOedssPbm9EpzsAjq+CSRtvyI+TsT6PWJuTvEUmW3T04zE03MexUW0OHQYPPMYXg5ZV28BAbUTu6pmlVYc=
